server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://lede-webservice.cerncfmkkqyp.ap-northeast-2.rds.amazonaws.com:3306/coupang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: a1234567
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전